# Generated by Django 4.2.28 on 2026-02-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PairMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(db_index=True, max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('pair', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['exchange', 'symbol'],
                'unique_together': {('exchange', 'pair')},
            },
        ),
    ]
